# Generated by Django 3.2.3 on 2021-05-27 08:11

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Покупатель клиента',
                'verbose_name_plural': 'Покупатели клиентов',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, verbose_name='UID')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('adequacy', models.FloatField(blank=True, null=True, verbose_name='Оценка за Качество / Адекватность')),
                ('decency', models.FloatField(blank=True, null=True, verbose_name='Оценка за Вежливость')),
                ('punctuality', models.FloatField(blank=True, null=True, verbose_name='Оценка за Пунктуальность')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Отзыв')),
                ('completed_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Отзыв о заказе',
                'verbose_name_plural': 'Отзывы о заказах',
            },
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='feedback_images')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('signedup_order_text', models.TextField(blank=True, verbose_name='Текст заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255, verbose_name='Название поля')),
            ],
            options={
                'verbose_name': 'Кастомное поле заказа',
                'verbose_name_plural': 'Кастомные поля заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderCustomFieldTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='text', max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип кастомного поля заказа',
                'verbose_name_plural': 'Типы кастомных полей заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Значение кастомного поля заказа',
                'verbose_name_plural': 'Значения кастомных полей заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Черновик заказа',
                'verbose_name_plural': 'Черновики заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Количество')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена заказа')),
            ],
            options={
                'verbose_name': 'Инвойс',
                'verbose_name_plural': 'Инвойс',
            },
        ),
        migrations.CreateModel(
            name='OrderPublish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Опубликованный заказ',
                'verbose_name_plural': 'Опубликованные заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
    ]
