# Generated by Django 3.2.3 on 2021-05-27 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('orders', '0001_initial'),
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def insertData(apps, schema_editor):
        OrderStatus = apps.get_model('orders', 'OrderStatus')
        OrderStatus.objects.get_or_create(id=1, title='Cоздан')
        OrderStatus.objects.get_or_create(id=2, title='Передан исполнителю')
        OrderStatus.objects.get_or_create(id=3, title='Выполнен')
        OrderStatus.objects.get_or_create(id=4, title='Ложный вызов')

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.AddField(
            model_name='orderpublish',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='orderpublish',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service', verbose_name='Услуга'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='orderdraft',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='ordercustomfieldvalue',
            name='custom_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ordercustomfield', verbose_name='Кастомное поле'),
        ),
        migrations.AddField(
            model_name='ordercustomfield',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='ordercustomfield',
            name='field_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.ordercustomfieldtypes', verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='order',
            name='custom_fields',
            field=models.ManyToManyField(db_table='order_to_custom_field', related_name='orders', to='orders.OrderCustomField'),
        ),
        migrations.AddField(
            model_name='order',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientstoredepartment', verbose_name='Отдел Торговой точки'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderstatus', verbose_name='Статус заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientstore', verbose_name='Торговая точка'),
        ),
        migrations.AddField(
            model_name='order',
            name='values',
            field=models.ManyToManyField(db_table='order_to_custom_field_value', related_name='orders', to='orders.OrderCustomFieldValue'),
        ),
        migrations.AddField(
            model_name='feedbackimage',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.feedback', verbose_name='Отзыв клиента'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(db_table='order_to_customer', to='orders.Order'),
        ),
        migrations.RunPython(insertData, reverse_func),
    ]
