# Generated by Django 3.2.3 on 2021-06-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210531_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercustomfield',
            options={'ordering': ['index_number'], 'verbose_name': 'Кастомное поле заказа', 'verbose_name_plural': 'Кастомные поля заказов'},
        ),
        migrations.AddField(
            model_name='ordercustomfield',
            name='index_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
