# Generated by Django 3.2.3 on 2021-06-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvoice',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название услуги'),
        ),
    ]
