# Generated by Django 3.2.3 on 2021-06-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderinvoice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercustomfield',
            name='size',
            field=models.PositiveIntegerField(default=1, verbose_name='Размер'),
        ),
    ]
