# Generated by Django 3.2.3 on 2021-07-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_send_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderXLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='orders_xls')),
            ],
        ),
    ]
