# Generated by Django 3.2.3 on 2021-07-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderxls'),
    ]

    def insertData(apps, schema_editor):
        OrderStatus = apps.get_model('orders', 'OrderStatus')
        OrderStatus.objects.filter(id=1).update(title='Создан')

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название статуса заказа'),
        ),
        migrations.RunPython(insertData, reverse_func),
    ]
