# Generated by Django 3.2.3 on 2021-07-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_orderstatus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data_sent',
            field=models.TextField(blank=True),
        ),
    ]
