# Generated by Django 3.2.3 on 2021-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_data_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvoice',
            name='rush_order_coefficient',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Коэф. Срочного заказа'),
        ),
    ]
