# Generated by Django 3.2.3 on 2021-07-18 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderinvoice_rush_order_coefficient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinvoice',
            name='rush_order_coefficient',
        ),
    ]
