# Generated by Django 3.2.3 on 2021-07-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_orderinvoice_rush_order_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена заказа'),
        ),
        migrations.AlterField(
            model_name='orderinvoice',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена заказа'),
        ),
        migrations.AlterField(
            model_name='orderinvoice',
            name='count',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество'),
        ),
    ]
