# Generated by Django 3.2.3 on 2021-07-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20210718_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackimage',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='feedback_images'),
        ),
    ]
