# Generated by Django 3.2.3 on 2021-07-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20210720_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='agreement_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackimage',
            name='from_executor',
            field=models.BooleanField(default=False),
        ),
    ]
