# Generated by Django 3.2.3 on 2021-07-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20210721_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='executor_fio',
            field=models.TextField(blank=True, null=True, verbose_name='Исполнитель'),
        ),
    ]
