# Generated by Django 3.2.3 on 2021-07-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_feedback_executor_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercustomfield',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Архивный'),
        ),
    ]
