# Generated by Django 3.2.3 on 2021-10-08 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clientstore_city'),
        ('orders', '0023_auto_20211008_0935'),
    ]

    def insertData(apps, schema_editor):
        Order = apps.get_model('orders', 'Order')
        OrderInvoice = apps.get_model('orders', 'OrderInvoice')

        for order in Order.objects.all():
            dep = order.department
            if dep:
                OrderInvoice.objects.filter(order=order).update(department=dep)

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.AddField(
            model_name='orderinvoice',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clientstoredepartment', verbose_name='Отдел Торговой точки'),
        ),
        migrations.RunPython(insertData, reverse_func)
    ]
