# Generated by Django 3.2.3 on 2022-03-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_orderinvoice_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='executor_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Исполнитель ID'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='executor_fio',
            field=models.TextField(blank=True, null=True, verbose_name='Исполнитель ФИО'),
        ),
    ]
