# Generated by Django 3.2.3 on 2022-03-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_city_options'),
        ('orders', '0025_auto_20220325_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinvoice',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.contractor', verbose_name='Подрядчик'),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='cost_contractor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за услугу для подрядчика'),
        ),
        migrations.AddField(
            model_name='orderinvoice',
            name='cost_signedup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за услугу для signedup'),
        ),
        migrations.AlterField(
            model_name='orderinvoice',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена за услугу для заказчика'),
        ),
    ]
