# Generated by Django 3.2.3 on 2022-07-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_ordercustomfield_show_in_xls'),
    ]

    def insertData(apps, schema_editor):
        OrderStatus = apps.get_model('orders', 'OrderStatus')
        OrderStatus.objects.filter(id=5).update(title='Не выполнено')
        OrderStatus.objects.get_or_create(id=6, title='Отменено')

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data_sent',
            field=models.TextField(blank=True, verbose_name='Данные, отправленные в сайнап'),
        ),
        migrations.AlterField(
            model_name='order',
            name='feedback_requested',
            field=models.BooleanField(default=False, verbose_name='Отзыв запрошен'),
        ),
        migrations.AlterField(
            model_name='order',
            name='send_sms',
            field=models.BooleanField(default=False, verbose_name='СМС отправлен'),
        ),
        migrations.RunPython(insertData, reverse_func),
    ]
