# Generated by Django 3.2.3 on 2023-05-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20220711_0841'),
    ]

    def insertData(apps, schema_editor):
        OrderStatus = apps.get_model('orders', 'OrderStatus')

        os = OrderStatus.objects.filter(id=7).first()
        if not os:
            OrderStatus.objects.create(id=7, title='Закреплен за исполнителем')

    def reverse_func(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(insertData, reverse_func)
    ]
