# Generated by Django 3.2.3 on 2023-10-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_alter_orderstatus_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderxls',
            name='file_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
